services:
  web:
    build:
      dockerfile: Dockerfile.web
    ports:
      - 8000:8000
  bot:
    build:
      dockerfile: Dockerfile.bot
  nginx:
    image: nginx:1.26.2
    container_name: nginx
    restart: always
    environment:
      - DOMAIN_NAME=telegrambottest.kvando.tech
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/certificate:/etc/ssl
