services:
  web:
    build:
      dockerfile: Dockerfile
    networks:
      - mynetwork
  nginx:
    image: nginx:1.26.2
    container_name: nginx
    restart: always
    environment:
      - DOMAIN_NAME=telegrambottest.kvando.tech
      - TZ=Europe/Moscow
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /root/certificate:/etc/ssl
      - /var/www/certbot:/usr/share/nginx/html
      - /etc/letsencrypt/tgbotkeys:/etc/ssl
      - /tg_landing/src/static:/usr/share/nginx/static
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
